name: Deploy to DigitalOcean Droplet
'on':
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    
      - name: Set CI environment variable to false
        run: echo "CI=false" >> $GITHUB_ENV
    
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and dependencies
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install project dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          SSH_PRIVATE_KEY: ${{ secrets.KEY }}
          source: ./build/
          target: ${{ secrets.SERVER_PATH }}
          SCRIPT_BEFORE: ls
          SCRIPT_AFTER: |
            sudo systemctl restart nginx
