name: Deploy to DigitalOcean Droplet
'on':
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    
      - name: Set CI environment variable to false
        run: echo "CI=false" >> $GITHUB_ENV
    
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and dependencies
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install project dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} # IP address of your Droplet
          username: ${{ secrets.USERNAME }} # Username to SSH into the Droplet
          key: ${{ secrets.KEY }} # SSH private key to authenticate
          script: |
            scp -r ./build/* ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/var/www/nevolodia.com/html/
            ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'sudo systemctl restart nginx'

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          SSH_PRIVATE_KEY: ${{ secrets.KEY }}
          source: ./build
          target: /var/www/nevolodia.com/html/
          SCRIPT_BEFORE: ls
          SCRIPT_AFTER: |
            sudo systemctl restart nginx
